defaults:
  - override hydra/job_logging: default
  - override hydra/launcher: basic

wandb:
  project: "loco_mujoco_td3" 

experiment:
  task_factory:
    name: RLFactory
    params: {}
  env_params:
    env_name: MjxUnitreeGo2
    horizon: 1000
    terminal_state_type: HeightBasedTerminalStateHandler
    goal_type: GoalRandomRootVelocity
    goal_params:
      visualize_goal: true
    headless: true
    reward_type: LocomotionReward
    reward_params:
      tracking_w_exp_xy: 4.0
      tracking_w_exp_yaw: 4.0
      tracking_w_sum_xy: 2.0
      tracking_w_sum_yaw: 1.0
      air_time_coeff: 0.1
      joint_acc_coeff: 2.0e-05
      air_time_max: 0.5
      joint_torque_coeff: 2.0e-07
      joint_position_limit_coeff: 2.0
      action_rate_coeff: 0.1
      symmetry_air_coeff: 0.005
      energy_coeff: 5.0e-05
  # Network Arch
  actor_hidden_dims: [512, 256]
  critic_hidden_dims: [512, 256]
  activation: relu
  
  # Optimizers
  actor_lr: 3e-4
  critic_lr: 3e-4
  
  # Replay Buffer and Batching
  buffer_size: 51200 # 2048000 # 1000 steps per environment
  batch_size: 32768 # 20480 
  learning_starts: 10 # 102400 # 100 steps per environment
  
  # TD3 Core Parameters
  gamma: 0.99
  tau: 0.1 # 0.005
  policy_noise: 0.001 # 0.01 # noise scale for the target computation
  noise_clip: 0.5 # 0.2
  std_min: 0.001 # min exploration noise with the env
  std_max: 0.4 # max exploration noise with the env
  policy_frequency: 2
  
  # General Training Config
  utd_ratio: 2
  num_envs: 128
  total_timesteps: 150000 # total interactions
  n_seeds: 1
  vmap_across_seeds: true
  normalize_env: true
  debug: false
  log_interval: 1e3 
  validation:
    active: false
    num_steps: 1000
    num_envs: 10
    num: 10 