defaults:
  - override hydra/job_logging: default
  - override hydra/launcher: basic

wandb:
  project: "loco_mujoco_fast_td3" # New project name

experiment:
  task_factory:
    name: RLFactory
    params: {}
  env_params:
    env_name: MjxUnitreeGo2
    horizon: 1000
    terminal_state_type: HeightBasedTerminalStateHandler
    goal_type: GoalRandomRootVelocity
    goal_params:
      visualize_goal: true
    headless: true
    reward_type: LocomotionReward
    reward_params:
      tracking_w_exp_xy: 4.0
      tracking_w_exp_yaw: 4.0
      tracking_w_sum_xy: 2.0
      tracking_w_sum_yaw: 1.0
      air_time_coeff: 0.1
      joint_acc_coeff: 2.0e-05
      air_time_max: 0.5
      joint_torque_coeff: 2.0e-07
      joint_position_limit_coeff: 2.0
      action_rate_coeff: 0.1
      symmetry_air_coeff: 0.005
      energy_coeff: 5.0e-05
  
  # --- FastTD3 Hyperparameters ---
  # Network Arch
  actor_hidden_dims: [512, 256]
  critic_hidden_dims: [512, 256]
  
  # Optimizers
  actor_lr: 3e-4
  critic_lr: 3e-4
  
  # Replay Buffer and Batching
  # buffer_size: 1000000
  buffer_size: 1000
  batch_size: 32768
  # learning_starts: 25000
  learning_starts: 250
  
  # TD3 Core Parameters
  gamma: 0.99
  tau: 0.005
  policy_noise: 0.2
  noise_clip: 0.5
  std_min: 0.1
  std_max: 0.4
  policy_frequency: 2
  
  # Distributional Critic Parameters
  num_atoms: 101
  v_min: -150.0
  v_max: 150.0
  
  # General Training Config
  utd_ratio: 4
  # num_envs: 2048
  num_envs: 100
  # total_timesteps: 10e7
  total_timesteps: 1e6
  normalize_env: true
  debug: false
  n_seeds: 1
  vmap_across_seeds: true
  validation:
    active: false
    num_steps: 100
    num_envs: 100
    num: 10 # set to 0 to disable validation
  log_interval: 100